# Generated by Django 6.0.6 on 2026-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(null=True, upload_to='menu/'),
        ),
    ]
